### ISSUE TITLE
Cannot access to URL

### ISSUE THREAD

**Issue by ignacioib1695** [vvaleed/relap#5]
To whom it may concern,

I am very grateful for the work you have done! It seems to be pretty useful after so many years of preparing the inputs by hand. However, I have to admit I have not been able to access the URL relap.codeplex.com/ where I should be able to get the latest version of the program (at least according to the user guide). 

If you can give me an advice or something it will be very helpful and I'll be totally grateful! 

Have a nice week!

**Comment by vvaleed** [comment]
Hi
Codeplex was merged into github. The code on github has been stale for many years now. If you need help, i can make changes to the code, or guide you to do it yourself.

Waleed

**Comment by ignacioib1695** [comment]
It would be great if you can guide me to install and use the software. On the other hand, do you know if there is anything else like this, in order to have a "friendlier" interface to generate inputs?

**Comment by seansimonian** [comment]
Hi Waleed, Sean here. I'm in the process of learning RELAP and would be interested in using your GUI, but am having a similar issue to Ignacioib1695. If you could help me install and get started with RIFGen, I would greatly appreciate it. Thank you for your time and help and looking forward to hearing from you.

**Comment by vvaleed** [comment]
Hi Sean, I can do a screenshare session with you anytime after 5pm (Pakistan time), let me know.

**Comment by seansimonian** [comment]
Hi Waleed, Sean here.

I appreciate your prompt reply. I can be available tomorrow at 7 PM
(Pakistan time). Would that work for you?

Thanks again for your time and help!

Sincerely,

Sean Simonian
Graduate Research Assistant
Thermal Hydraulics V&V Laboratory
<http://people.tamu.edu/~mark.kimber/index.html>
Texas A&M University - Department of Nuclear Engineering
<https://engineering.tamu.edu/nuclear/index.html>

**Comment by vvaleed** [comment]
7pm done

**Comment by seansimonian** [comment]
Perfect! Thank you so much. If Zoom is okay we can use my meeting room, the
link is below:

https://tamu.zoom.us/j/5272470436?pwd=bmM2cW9FcGgrbkh2dk1uRy9kQTRtUT09
Meeting ID: 527 247 0436
Passcode: ZPssn3

If you would prefer another platform please let me know and I will see you
there.

Sincerely,

Sean Simonian
Graduate Research Assistant
Thermal Hydraulics V&V Laboratory
<http://people.tamu.edu/~mark.kimber/index.html>
Texas A&M University - Department of Nuclear Engineering
<https://engineering.tamu.edu/nuclear/index.html>

**Comment by vvaleed** [comment]
Yes, zoom works.

**Comment by PugachevMA** [comment]
Greetings!

I am reaching out to kindly request the latest version of your software. I have encountered an issue with the current version: it is unstable and unexpectedly quits, sometimes preventing data from being saved. When saving is possible, the saved files contain errors.

I would be extremely grateful for your assistance in resolving this issue, as it would significantly improve my work efficiency.

Sincerely,
PMA

**Comment by vvaleed** [comment]
Hi Pugachev,
What version of Windows are you on? Can you share error details?

Regards,
Waleed

**Comment by PugachevMA** [comment]
Hello VValeed,

Thank you for your feedback. Windows 10  (Windows 10 Pro Build 19041.vb release.191206-1406) is installed on my computer. Every time I try to open a saved file, the following error occurs:

```
System.ArgumentException: ValueObject property expects either null/nothing value or double type.
   at DevComponents.Editors.DoubleInput.set_ValueObject(Object value)
   at DevComponents.Editors.DoubleInput.set_Text(String value)
   at RELAP.frmInitialSettings.loadsettings()
   at RELAP.FormMain.LoadF(String caminho)
   at RELAP.FormMain.LoadFileDialog()
   at RELAP.FormMain.OpenToolStripButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

``` 

This error also appears sometimes when I start working in the program. Additionally, the program gives a warning when using a dot as a decimal separator instead of a comma. Is there a way to fix this? Generally, replacing commas with dots is not an issue, but I had to ask.

I really liked your version of the GUI for RELAP5 input deck, thank you for providing open access!

**Comment by PugachevMA** [comment]
Another error when I save file:
"Erro ао salvar arquivo: Ссылка на объект не указывает на экземпляр объекта (An object reference does not point to an instance of an object)."
